spring:
  profiles:
    active: dev
  application:
    name: login-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qaqchat
    username: ${qaqchat.datasource.username}
    password: ${qaqchat.datasource.password}
  data:
    redis:
      host: ${qaqchat.redis.host}
      port: ${qaqchat.redis.port}
      password: ${qaqchat.redis.password}

qaqchat:
  jwt:
    secret-key: ${qaqchat.jwt.secret-key}
    expiration-time: 86400000
  email-sender:
    host: ${qaqchat.email-sender.host}
    port: ${qaqchat.email-sender.port}
    from: ${qaqchat.email-sender.from}
    password: ${qaqchat.email-sender.password}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.github.qaqchat.logindemo.controller
