spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

qaqchat:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME:86400000}
  email-sender:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT:465}
    from: ${EMAIL_FROM}
    password: ${EMAIL_PASSWORD}
