name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress -DskipTests

      - name: Check JAR file
        run: |
          if [ ! -f target/*.jar ]; then
            echo "JAR file not found in target/ directory!"
            exit 1
          fi
      - name: Upload and Deploy
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET: ${{ secrets.DEPLOY_TARGET_DIR }}
        run: |
          mkdir -p ~/.ssh

          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan ${HOST} >> ~/.ssh/known_hosts
          
          rsync -avz --progress ./target/*.jar ${USERNAME}@${HOST}:${TARGET}/build/
          rsync -avz Dockerfile ${USERNAME}@${HOST}:${TARGET}/build/

          ssh ${USERNAME}@${HOST}:${TARGET}/deploy.sh
